### ISSUE TITLE
Problem installing 3.4.11

### ISSUE THREAD

**Issue by nekosaur** [Legrandin/pycryptodome#129]
I'm getting the following error when trying to install pycryptodomex 3.4.11 on debian using pip

```
Collecting pycryptodomex
  Using cached pycryptodomex-3.4.11.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-zFXyd7/pycryptodomex/setup.py", line 107, in <module>
        for line in open(os.path.join("lib", "Crypto", "__init__.py")):
    IOError: [Errno 2] No such file or directory: 'lib/Crypto/__init__.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-zFXyd7/pycryptodomex/
```

Looking at the contents of the package, there is no `lib/Crypto` folder, but a `lib/Cryptodome` folder. I checked the contents of pycryptodomex 3.4.9 and there the folder is named `lib/Crypto`. Am I missing something obvious?

**Comment by Legrandin** [comment]
Thanks for reporting. 3.4.12 is out and should fix that.
