### ISSUE TITLE
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb'

### ISSUE THREAD

**Issue by GrayLand119** [Legrandin/pycryptodome#155]
## About Error
I used `pycrytodome` in `pycharm` is fine, but when I use `pyinstaller` to package my program,
(With command: `pyinstaller -F CryptoTest.py`),After it build successed,  I execute the program and got the error below:
```shell
Traceback (most recent call last):
  File "CryptoTest.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\python3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\Crypto\Cipher\__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\python3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\Crypto\Cipher\_mode_ecb.py", line 46, in <module>
  File "site-packages\Crypto\Util\_raw_api.py", line 258, in load_pycryptodome_raw_lib
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cp36-win32.pyd': cannot load library 'C:\Users\grayland\AppData\Local\Temp\_MEI16642\Crypto\Util\..\Cipher\_raw_ecb.cp36-win32.pyd': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'C:\\Users\\grayland\\AppData\\Local\\Temp\\_MEI16642\\Crypto\\Util\\..\\Cipher\\_raw_ecb.cp36-win32.pyd', Trying '_raw_ecb.pyd': cannot load library 'C:\Users\grayland\AppData\Local\Temp\_MEI16642\Crypto\Util\..\Cipher\_raw_ecb.pyd': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'C:\\Users\\grayland\\AppData\\Local\\Temp\\_MEI16642\\Crypto\\Util\\..\\Cipher\\_raw_ecb.pyd'
[7400] Failed to execute script CryptoTest
```

## CryptoTest.py

Here is my codes:

```python
from Crypto.Cipher import AES
from Crypto.Util.Padding import *

if __name__ == '__main__':

    key = b'1234567890123456'
    iv = b'1234567890123456'
    cryptor = AES.new(key,AES.MODE_CBC, iv)
    a = 'aaaaa'
    padA = pad(a.encode(), AES.block_size)
    enA = cryptor.encrypt(padA)
    print('Result = ', enA)
```
And It run fine in `pycharm`:
```shell
pydev debugger: process 7320 is connecting

Connected to pydev debugger (build 181.4445.76)
Result =  b'{\x90\xa9Ln\xd1{F\xb3/N\xa1s\x98\xc6\xce'

Process finished with exit code 0
```

## Python Env:
```shell
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 16:07:46) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```
## Pycryptodome Version:
```shell
Name: pycryptodome
Version: 3.6.0
Summary: Cryptographic library for Python
Home-page: http://www.pycryptodome.org
Author: Helder Eijs
Author-email: helderijs@gmail.com
License: UNKNOWN
Location: c:\python3\lib\site-packages
```
## PyInstaller Version:
```shell
Name: PyInstaller
Version: 3.3.1
```

**Comment by Legrandin** [comment]
Recently, the `pyinstaller` team has added a couple of hooks to support `pycryptodome`. However, there is no release available with them yet.

What you could do is:
1) Download the hook for the `Crypto` namespace from the dev branch:
    * https://raw.githubusercontent.com/pyinstaller/pyinstaller/develop/PyInstaller/hooks/hook-Crypto.py
2) Run `pyinstaller` with the option `--runtime-hook <path/to/hook-Crypto.py>`

The hook should pull in the missing native modules.

I did not try myself, but there are good chances it works.

**Comment by GrayLand119** [comment]
@Legrandin Thanks a lot~ I just see you comment. The problem solved a few minutes ago, I fixed this problem by 2 steps:

1. `Copy Crypto Folder` and rename `Cryptodome` in the python's directory `../site-packages`
2. Open the file `./site-packages/Cryptodome/Util/_raw_api.py`, and rename imports from "Crypto" to "Cryptodome".

This repository is so good! It help me a lot, Thank you for all of your efforts~~

**Comment by fpan-splunk** [comment]
Hi @Legrandin how to solve the same issue if I want to embed pycryptodome in my own package? thanks!

**Comment by kuguma** [comment]
FYI:
pycryptodomex may solve the problem.
https://pypi.org/project/pycryptodomex/
