### ISSUE TITLE
Unable to bundle pycryptodome using py2exe

### ISSUE THREAD

**Issue by Prev-I** [Legrandin/pycryptodome#161]
I've made some testing trying to replace pycrypto inside our software.
With the latest release of pycryptodome I've got different error than the one reported in #14 

My enviroment is the following:
```
python 2.7.14-win32
pycryptodome==3.6.1
py2exe-py2==0.6.9
esky==0.7.4
```
the exe is builded correctly but when I launch it I've got this stacktrace:
```
Traceback (most recent call last):
  File "__main__.py", line 555, in <module>
  File "__main__.py", line 120, in bootstrap
  File "__main__.py", line 144, in chainload
  File "__main__.py", line 551, in _chainload
  File "myapp.pyw", line 35, in <module>
  File "zipextimporter.pyc", line 82, in load_module
  File "Crypto\Cipher\__init__.pyc", line 3, in <module>
  File "zipextimporter.pyc", line 82, in load_module
  File "Crypto\Cipher\_mode_ecb.pyc", line 29, in <module>
  File "zipextimporter.pyc", line 82, in load_module
  File "Crypto\Util\_raw_api.pyc", line 161, in <module>
  File "ctypes\__init__.pyc", line 375, in __getattr__
  File "ctypes\__init__.pyc", line 380, in __getitem__
AttributeError: function 'PyObject_GetBuffer' not found
```
any suggestions?

**Comment by Legrandin** [comment]
This seems an issue unrelated to PyCryptodome: for example see https://github.com/pallets/flask/issues/1966 .

In any case, I doubt that py2exe will work in the end. Any chance you can switch to [pyinstaller](https://www.pyinstaller.org/)?

**Comment by Prev-I** [comment]
unfortunately our software used esky (now a defunct project) which is not working with pyinstaller.
I could give a try to change our deploy chain with more modern tools but that is outside the scope of this issue.

Given the fact that is not related to pycryptodome I'm closing this issue. Thanks
