### ISSUE TITLE
Strange issues when debugging on windows

### ISSUE THREAD

**Issue by oOve** [Legrandin/pycryptodome#171]
I have created a RSA key and exported to pem.
When I run my python script calling RSA.importKey using pycharms debug environment it fails with RSA key format is not supported.
When I run my python script through "run" or regular python this works.

Here is the output from pycharms debug session:
```
D:\Anaconda3_64\python.exe "C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.3\helpers\pydev\pydevd.py" --multiproc --qt-support --client 127.0.0.1 --port 59397 --file D:/src/createLicenseFile.py
warning: Debugger speedups using cython not found. Run '"D:\Anaconda3_64\python.exe" "C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.3\helpers\pydev\setup_cython.py" build_ext --inplace' to build.
pydev debugger: process 18620 is connecting

Connected to pydev debugger (build 171.4424.42)
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.3\helpers\pydev\pydevd.py", line 1585, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.3\helpers\pydev\pydevd.py", line 1015, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/src/createLicenseFile.py", line 50, in <module>
    key = RSA.importKey(open(private_key_name).read())
  File "D:\Anaconda3_64\lib\site-packages\Cryptodome\PublicKey\RSA.py", line 736, in import_key
    return _import_keyDER(der, passphrase)
  File "D:\Anaconda3_64\lib\site-packages\Cryptodome\PublicKey\RSA.py", line 679, in _import_keyDER
    raise ValueError("RSA key format is not supported")
ValueError: RSA key format is not supported
```

I get the same message when loading my public key from pem as well, but when loading the publik key from 'ssh-rsa asdfasdf' format works.

**Comment by Legrandin** [comment]
This is fixed in v3.6.2 (by adding more checks to avoid MPIR).
