### ISSUE TITLE
SelfTest failed

### ISSUE THREAD

**Issue by yimeantw** [Legrandin/pycryptodome#222]
I report my environment and test result as following. Please help me to solve it. Many thanks.

OS: Windows 10 pro x64
CPU: Intel i5-6200U
RAM: 8GB

C:\Users\ACER>python -m Crypto.SelfTest
Skipping GMP tests (ctypes.util.find_library() did not manage to locate a library called 'gmp')
........//.......
======================================================================
ERROR: runTest (Crypto.SelfTest.Hash.test_HMAC.ByteArrayTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\ACER\Anaconda3\lib\site-packages\Crypto\SelfTest\Hash\test_HMAC.py", line 315, in runTest
    h2 = HMAC.new(key_ba, data_ba)
  File "C:\Users\ACER\Anaconda3\lib\site-packages\Crypto\Hash\HMAC.py", line 213, in new
    return HMAC(key, msg, digestmod)
  File "C:\Users\ACER\Anaconda3\lib\site-packages\Crypto\Hash\HMAC.py", line 83, in __init__
    key_0_ipad = strxor(key_0, b"\x36" * len(key_0))
TypeError: argument 1 must be bytes, not bytearray

======================================================================
ERROR: test_bytearray (Crypto.SelfTest.Util.test_strxor.StrxorTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\ACER\Anaconda3\lib\site-packages\Crypto\SelfTest\Util\test_strxor.py", line 71, in test_bytearray
    self.assertEqual(strxor(term1_ba, term2), result)
TypeError: argument 1 must be bytes, not bytearray

======================================================================
ERROR: test_memoryview (Crypto.SelfTest.Util.test_strxor.StrxorTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\ACER\Anaconda3\lib\site-packages\Crypto\SelfTest\Util\test_strxor.py", line 79, in test_memoryview
    self.assertEqual(strxor(term1_mv, term2), result)
TypeError: argument 1 must be bytes, not memoryview

======================================================================
ERROR: test_bytearray (Crypto.SelfTest.Util.test_strxor.Strxor_cTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\ACER\Anaconda3\lib\site-packages\Crypto\SelfTest\Util\test_strxor.py", line 110, in test_bytearray
    self.assertEqual(strxor_c(term1_ba, 65), result)
TypeError: argument 1 must be bytes, not bytearray

======================================================================
ERROR: test_memoryview (Crypto.SelfTest.Util.test_strxor.Strxor_cTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\ACER\Anaconda3\lib\site-packages\Crypto\SelfTest\Util\test_strxor.py", line 117, in test_memoryview
    self.assertEqual(strxor_c(term1_mv, 65), result)
TypeError: argument 1 must be bytes, not memoryview

----------------------------------------------------------------------
Ran 39825 tests in 150.468s

FAILED (errors=5)
Traceback (most recent call last):
  File "C:\Users\ACER\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\ACER\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\ACER\Anaconda3\lib\site-packages\Crypto\SelfTest\__main__.py", line 35, in <module>
    SelfTest.run(stream=sys.stdout, verbosity=1, config=config)
  File "C:\Users\ACER\Anaconda3\lib\site-packages\Crypto\SelfTest\__init__.py", line 77, in run
    raise SelfTestError("Self-test failed", result)
Crypto.SelfTest.SelfTestError: ('Self-test failed', <unittest.runner.TextTestResult run=39825 errors=5 failures=0>)

**Comment by Legrandin** [comment]
Could you please update the `cffi` package to the latest version (or remove it completely), and reopen if this is still an issue.

**Comment by i-pk** [comment]
i removed the cffi library, still getting same error
