### ISSUE TITLE
pycryptodom fails to run with CFFI and PYTHONOPTIMIZE=2 due to using cffi in-line ABI mode

### ISSUE THREAD

**Issue by schlenk** [Legrandin/pycryptodome#228]
Hi,

when using the cffi backend with optimize (PYTHONOPTIMIZE=2) the loading of cryptodome fails due to a bug in pycparser (see https://github.com/eliben/pycparser/pull/198 ). See below for the error.

It should be possible to work around that issue, if pycryptodome used the 'out-of-line' feature of cffi, to compile/produce the API wrappers upfront during installation. See https://cffi.readthedocs.io/en/latest/cdef.html#ffibuilder-set-source-preparing-out-of-line-modules

As a side effect, using the out-of-line mode for cffi would speed up import times and reduce the memory footprint.

`
C:\>c:\Python27_x64\python.exe -OO -m Cryptodome.SelfTest
`
This leads to an error on load.
`
c:\Python27_x64\lib\site-packages\pycparser\c_parser.py:20: RuntimeWarning: parsing methods must have __doc__ for pycparser to work properly
  class CParser(PLYParser):
WARNING: There was a problem loading the table file: KeyError('p_direct_id_declarator_1',)
`

**Comment by Legrandin** [comment]
Fixed with be4088c.

**Comment by ComputerUser-CU** [comment]
Hello,

I am facing this issue on Python 3.4.

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\Crypto\Util\_raw_api.py", line 83, in <module>
    raise ImportError("CFFI with optimize=2 fails due to pycparser bug.")
ImportError: CFFI with optimize=2 fails due to pycparser bug.

I am using pyCryptodome with Youtube-DL. I've built a local EXE of Youtube-DL using py2exe. So Py2exe should be putting PyCryptodome into the single EXE. When I run the EXE with any command, I get this error. For example,

C:\Users\Beyonce\AppData\Roaming\youtube-dl>youtube-dl.exe https://www.youtube.com/watch?v=qqWSMAoQOVg
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\Crypto\Util\_raw_api.py", line 83, in <module>
    raise ImportError("CFFI with optimize=2 fails due to pycparser bug.")
ImportError: CFFI with optimize=2 fails due to pycparser bug.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "__main__.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\zipextimporter.py", line 86, in load_module
    return zipimport.zipimporter.load_module(self, fullname)
  File "C:\Users\Beyonce\youtube-dl\youtube_dl\__init__.py", line 15, in <module>
    from .options import (
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\zipextimporter.py", line 86, in load_module
    return zipimport.zipimporter.load_module(self, fullname)
  File "C:\Users\Beyonce\youtube-dl\youtube_dl\options.py", line 8, in <module>
    from .downloader.external import list_external_downloaders
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\zipextimporter.py", line 86, in load_module
    return zipimport.zipimporter.load_module(self, fullname)
  File "C:\Users\Beyonce\youtube-dl\youtube_dl\downloader\__init__.py", line 5, in <module>
    from .hls import HlsFD
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\zipextimporter.py", line 86, in load_module
    return zipimport.zipimporter.load_module(self, fullname)
  File "C:\Users\Beyonce\youtube-dl\youtube_dl\downloader\hls.py", line 6, in <module>
    from Crypto.Cipher import AES
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\zipextimporter.py", line 86, in load_module
    return zipimport.zipimporter.load_module(self, fullname)
  File "C:\Python34\lib\site-packages\Crypto\Cipher\__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\zipextimporter.py", line 86, in load_module
    return zipimport.zipimporter.load_module(self, fullname)
  File "C:\Python34\lib\site-packages\Crypto\Cipher\_mode_ecb.py", line 29, in <module>
    from Crypto.Util._raw_api import (load_pycryptodome_raw_lib,
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\zipextimporter.py", line 86, in load_module
    return zipimport.zipimporter.load_module(self, fullname)
  File "C:\Python34\lib\site-packages\Crypto\Util\_raw_api.py", line 200, in <module>
    _PyObject_GetBuffer = ctypes.pythonapi.PyObject_GetBuffer
  File "C:\Python34\lib\ctypes\__init__.py", line 364, in __getattr__
    func = self.__getitem__(name)
  File "C:\Python34\lib\ctypes\__init__.py", line 369, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'PyObject_GetBuffer' not found
'rct' is not recognized as an internal or external command,
operable program or batch file.
'q' is not recognized as an internal or external command,
operable program or batch file.
'esrc' is not recognized as an internal or external command,
operable program or batch file.
'source' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.
'cad' is not recognized as an internal or external command,
operable program or batch file.
'uact' is not recognized as an internal or external command,
operable program or batch file.
'ved' is not recognized as an internal or external command,
operable program or batch file.
'url' is not recognized as an internal or external command,
operable program or batch file.
'usg' is not recognized as an internal or external command,
operable program or batch file.
