### ISSUE TITLE
Error during RSA signature: 'RsaKey' object has no attribute 'x'

### ISSUE THREAD

**Issue by SukkoPera** [Legrandin/pycryptodome#294]
Using Pycryptodome 3.8.2, I'm trying to sign something with RSA. Key was generated with OpenSSL and is in PEM format.

```
from Crypto.PublicKey import RSA
from Crypto.Hash import SHA256
from Crypto.Signature import DSS

PRIVKEY = """-----BEGIN RSA PRIVATE KEY-----
<snip>
-----END RSA PRIVATE KEY-----
"""

message = "fhhfuiohgsduiohgriohguiowrhgiorghiowerfejkdpfo"
key = RSA.importKey (PRIVKEY)
h = SHA256.new (message)
signer = DSS.new (key, 'fips-186-3')
signature = signer.sign (h)
```

This fails with:

```
Traceback (most recent call last):
  File "test_sig.py", line 50, in <module>
    signer = DSS.new (key, 'fips-186-3')
  File "C:\Python27\lib\site-packages\Crypto\Signature\DSS.py", line 396, in new
    private_key = getattr(key, private_key_attr)
AttributeError: 'RsaKey' object has no attribute 'x'
```

**Comment by SukkoPera** [comment]
Sorry, now I see I need to use PKCS#1 for RSA signatures. Forget this :).
