### ISSUE TITLE
AttributeError: 'EccPoint' object has no attribute '_mpz_p'

### ISSUE THREAD

**Issue by LuminousXLB** [Legrandin/pycryptodome#318]
Here's what I did

```console
$ cat test.py
from Crypto.PublicKey import ECC

if __name__ == "__main__":
    ka = ECC.generate(curve='p256')
    kb = ECC.generate(curve='p256')

    print(ka.d*kb.pointQ)
$ python3 test.py
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    print(ka.d*kb.pointQ)
  File "/home/ncl/.local/lib/python3.6/site-packages/Crypto/Math/_IntegerGMP.py", line 311, in __mul__
    term = IntegerGMP(term)
  File "/home/ncl/.local/lib/python3.6/site-packages/Crypto/Math/_IntegerGMP.py", line 167, in __init__
    _gmp.mpz_init_set(self._mpz_p, value._mpz_p)
AttributeError: 'EccPoint' object has no attribute '_mpz_p'
$ pip3 freeze | grep crypto
asn1crypto==0.24.0
cryptography==2.1.4
pycrypto==2.6.1
pycryptodome==3.8.2

```

**Comment by Legrandin** [comment]
Try to invert the terms in the multiplication, like this:

    print(kb.pointQ * ka.d)

**Comment by LuminousXLB** [comment]
> Try to invert the terms in the multiplication, like this:
> 
> ```
> print(kb.pointQ * ka.d)
> ```

Yes, it works. Thanks!
