### ISSUE TITLE
key_to_english does not raise error when feeding with invalid data (length must be a multiple of 8)

### ISSUE THREAD

**Issue by vstoykovbg** [Legrandin/pycryptodome#340]
Most users do not read the documentation thoroughly. 

This is why functions should be idiot-proof.

I just stumbled upon this bug. Tried to feed `key_to_english` with invalid data and was wondering why the reverse function (`english_to_key`) complain about parity error.

Here is my code I wrote because I did not RTFM before coding. (I just glanced it.)
```
#!/usr/bin/python3

import os
import binascii
from Cryptodome.Util import RFC1751

#key = os.urandom(16) # Generate 16 random bytes (128 bits)
key = "Test hehe".encode("utf8")

print ("Hex Key:\t",binascii.hexlify(key))

y = RFC1751.key_to_english(key)
print ("Plain text key:\t",y)

key = RFC1751.english_to_key(y)
print ("\n\nReverse:\t",binascii.hexlify(key))
```

```
$ ./crypto-magic-test-cryptodome.py
Hex Key:	 b'546573742068656865'
Plain text key:	 BEAK NET SITE TIN FREE LUND CHAT A A A A A
Traceback (most recent call last):
  File "./crypto-magic-test-cryptodome.py", line 15, in <module>
    key = RFC1751.english_to_key(y)
  File "/usr/lib/python3/dist-packages/Cryptodome/Util/RFC1751.py", line 116, in english_to_key
    raise ValueError("Parity error in resulting key")
ValueError: Parity error in resulting key
```

Tested it with `Crypto.Util`, the same bug is present. https://github.com/dlitz/pycrypto/issues/295

**Comment by Legrandin** [comment]
Fixed in v3.9.4.
