### ISSUE TITLE
Python 3.5: problems with cffi-1.7.0 vs missing cffi module

### ISSUE THREAD

**Issue by bernhard-42** [Legrandin/pycryptodome#37]
There is a problem with Anaconda 4.2.0 version of python 3.5:

First example is Python 3.5 from Anaconda 4.2.0

``` python
Python 3.5.2 |Anaconda 4.2.0 (x86_64)| (default, Jul  2 2016, 17:52:12)
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

>>> from Crypto.Protocol.KDF import scrypt
>>> passphrase = b"secret passphrase"
>>> salt = b"a bit of salt"
>>> scrypt(passphrase, salt, 32, N=1024, r=8, p=1)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/lib/python3.5/site-packages/Crypto/Protocol/KDF.py", line 387, in scrypt
    for x in range(0, len(blocks), 128 * r)])
  File "/opt/anaconda3/lib/python3.5/site-packages/Crypto/Protocol/KDF.py", line 387, in <listcomp>
    for x in range(0, len(blocks), 128 * r)])
  File "/opt/anaconda3/lib/python3.5/site-packages/Crypto/Protocol/KDF.py", line 323, in _scryptROMix
    t = [strxor(x[idx], v[j][idx]) for idx in range(len_x)]
  File "/opt/anaconda3/lib/python3.5/site-packages/Crypto/Protocol/KDF.py", line 323, in <listcomp>
    t = [strxor(x[idx], v[j][idx]) for idx in range(len_x)]
TypeError: argument 1 must be bytes, not _cffi_backend.CDataOwn
```

Compared to python 3.5 (installed by homebrew)

``` python
Python 3.5.2 (default, Oct 11 2016, 05:05:28)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

>>> from Crypto.Protocol.KDF import scrypt
>>> passphrase = b"secret passphrase"
>>> salt = b"a bit of salt"
>>> scrypt(passphrase, salt, 32, N=1024, r=8, p=1)

b'\x1c\x87\x1dn\x80\x16\xe8\x10\xac^v\x08\xc8x,u\x19\x16\xf1\xed\x86\xdf\xd3_Y$\xd6e`#\xec\x88'
```

In both cases I installed PyCryptodome by using `pip install pycryptodome`

It looks like it can be reduced to `Crypto.Util._raw_api.create_string_buffer`:

Anaconda Python:

``` python
Python 3.5.2 |Anaconda 4.2.0 (x86_64)| (default, Jul  2 2016, 17:52:12)
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

>>> from Crypto.Util._raw_api import create_string_buffer
>>> type(create_string_buffer(64))

<class '_cffi_backend.CDataOwn'>
```

Homebrew Python:

``` python
Python 3.5.2 (default, Oct 11 2016, 05:05:28)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

>>> from Crypto.Util._raw_api import create_string_buffer
>>> type(create_string_buffer(64))

<class 'ctypes.c_char_Array_64'>
```

Going into detail, one sees, Anaconda is coming with cffi-1.7.0 while Homebrew python doesn't have cffi. Now in _raw_api cffi gets imported in a try loop. So Anaconda uses cffi (and fails) while Homebrew doesn't (and succeeds).

**Comment by bernhard-42** [comment]
This isn't a python 3.5 or cffi issue. 
Pycryptodome needs to be installed in Anaconda as pycryptodomex to avoid issues with preinstalled pycrypto
