### ISSUE TITLE
Crypto (+ Cryptodome) usage issue [ ValueError: invalid literal for int() with base 10: '' ]

### ISSUE THREAD

**Issue by sunandosamaddar** [Legrandin/pycryptodome#371]
Hi, I'm trying to create cookie signatures in my web app with both `Crypto` and `Cryptodome` (using one at a time) package in a Python 2.7 venv, but there seems to be some problem I'm not sure how to handle. This is my first experience with this package.

**Traceback**
```
Traceback (most recent call last):
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 311, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/Users/sunandosamaddar/google_drive/py/webapp2_apps/hellowebapp2/main.py", line 4, in <module>
    from Cryptodome.Hash import SHA256
  File "/Users/sunandosamaddar/google_drive/py/webapp2_apps/hellowebapp2/server/lib/Cryptodome/Hash/SHA256.py", line 23, in <module>
    from Cryptodome.Util._raw_api import (load_pycryptodome_raw_lib,
  File "/Users/sunandosamaddar/google_drive/py/webapp2_apps/hellowebapp2/server/lib/Cryptodome/Util/_raw_api.py", line 165, in <module>
    import ctypes
  File "/Users/sunandosamaddar/opt/miniconda3/envs/py27/lib/python2.7/ctypes/__init__.py", line 29, in <module>
    if int(_os.uname()[2].split('.')[0]) < 8:
ValueError: invalid literal for int() with base 10: ''
```

**Code**
```
key = RSA.generate(2048)
key = key.export_key(passphrase=*****, pkcs=8, protection="scryptAndAES128-CBC")
h = SHA256.new(
    security.generate_random_string(length=32, pool='ASCII_PRINTABLE'))
signature = pkcs1_15.new(key).sign(h)
```

**Comment by Varbin** [comment]
Your code has an issue you can fix and one is a problem of your Python installation (or worse, MacOS):
1. You try to use `pkcs1_15.new()` with your exported key (which is type `bytes` or `str`), but it takes the RSA key object instead. If have used a recent edition of Python (2.7 is EOL, by the way), you can use type annotations and run linters like [mypy](http://mypy-lang.org/) to detect those issues.
2. There seems to be a problem with your Python installation (or OS X), as the the [exception is raised in the ctypes module](https://github.com/python/cpython/blob/00923c63995e34cdc25d699478f113de99a69df9/Lib/ctypes/__init__.py#L29) of Python itself (not really related to neither your code or Pycryptodome).

Correct code, fixing the first problem:

```python
from Cryptodome.Hash import SHA256
from Cryptodome.PublicKey import RSA
from Cryptodome.Signature import pkcs1_5

key = RSA.generate(3072)
exported_key = key.export_key(passphrase="*****", pkcs=8, protection="scryptAndAES128-CBC")
signature = pkcs1_15.new(key).sign(SHA256.new(b"Cookie"))
```

**Comment by sunandosamaddar** [comment]
Thanks Varbin for **1** and **2**. In case of 2, see this.
```
>>> import os
>>> os.uname().release.split('.')[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'tuple' object has no attribute 'release'
```

**Comment by Varbin** [comment]
@sunandosamaddar I linked the Python 3 ctypes, thus it cannot work. The Python 2 would be 

```python
import os
os.uname()[2].split('.')[0]
```

**Comment by texadactyl** [comment]
@sunandosamaddar
Upgraded yet to Python 3?  Recall that Python 2 is deprecated.
Your code as corrected by @Varbin works just fine in Python 3 in a command line or using the Spyder IDE (recommended).
Time to close this issue?

```
import os
from Crypto.Hash import SHA256
from Crypto.PublicKey import RSA
from Crypto.Signature import pkcs1_15

key = RSA.generate(3072)
exported_key = key.export_key(passphrase="Elephino", pkcs=8, protection="scryptAndAES128-CBC")
signature = pkcs1_15.new(key).sign(SHA256.new(b"Cookie"))
print("Signature length:", len(signature))
print("os.uname().release.split('.'): ", os.uname().release.split('.'))
print("os.uname().release.split('.')[0]: ", os.uname().release.split('.')[0])
```

Stdout for me (Xubuntu 20.04 LTS with kernel 5.4.0-24-generic):
```
Signature length: 384
os.uname().release.split('.'):  ['5', '4', '0-24-generic']
os.uname().release.split('.')[0]:  5
```

**Comment by texadactyl** [comment]
@Legrandin Another one that can be closed due to lack of participation by the issue originator.
