### ISSUE TITLE
Wrong cffi version assertion

### ISSUE THREAD

**Issue by wikier** [Legrandin/pycryptodome#41]
With a regular installation from a project that depends on `pycryptodome` (rohe/pyjwkest#75) I get a `cffi` assertion error:

```
>>> import jwkest.jwk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wikier/.local/lib/python3.5/site-packages/jwkest/jwk.py", line 11, in <module>
    from Cryptodome.PublicKey import RSA
  File "/home/wikier/.local/lib/python3.5/site-packages/Cryptodome/PublicKey/RSA.py", line 79, in <module>
    from Cryptodome.IO import PKCS8, PEM
  File "/home/wikier/.local/lib/python3.5/site-packages/Cryptodome/IO/PKCS8.py", line 73, in <module>
    from Cryptodome.IO._PBES import PBES1, PBES2, PbesError
  File "/home/wikier/.local/lib/python3.5/site-packages/Cryptodome/IO/_PBES.py", line 44, in <module>
    from Cryptodome.Cipher import DES, ARC2, DES3, AES
  File "/home/wikier/.local/lib/python3.5/site-packages/Cryptodome/Cipher/__init__.py", line 78, in <module>
    from Cryptodome.Cipher._mode_ecb import _create_ecb_cipher
  File "/home/wikier/.local/lib/python3.5/site-packages/Cryptodome/Cipher/_mode_ecb.py", line 29, in <module>
    from Cryptodome.Util._raw_api import (load_pycryptodome_raw_lib,
  File "/home/wikier/.local/lib/python3.5/site-packages/Cryptodome/Util/_raw_api.py", line 39, in <module>
    ffi = FFI()
  File "/home/wikier/.local/lib/python3.5/site-packages/cffi/api.py", line 59, in __init__
    "version mismatch, %s != %s" % (backend.__version__, __version__)
AssertionError: version mismatch, 1.7.0 != 1.8.3
```

Which I manage to fix by manually forcing the version:

    pip install cffi==1.7.0

So that needs to be declared in the package dependencies.

**Comment by Legrandin** [comment]
I guess you were on Debian: the way they used to package `cffi` is probably the cause. See also this other bug report: https://github.com/pyca/cryptography/issues/2491 .
