### ISSUE TITLE
import_key says RSA key format not supported

### ISSUE THREAD

**Issue by jsahil730** [Legrandin/pycryptodome#419]
Traceback (most recent call last):
  File "CERTainly not.py", line 5, in <module>
    r = RSA.import_key(f.read())
  File "/usr/local/lib/python3.6/dist-packages/Crypto/PublicKey/RSA.py", line 783, in import_key
    return _import_keyDER(extern_key, passphrase)
  File "/usr/local/lib/python3.6/dist-packages/Crypto/PublicKey/RSA.py", line 682, in _import_keyDER
    raise ValueError("RSA key format is not supported")
ValueError: RSA key format is not supported

I am getting this error with a certain DER public key certificate, present in the attached zip
[2048b-rsa.zip](https://github.com/Legrandin/pycryptodome/files/4652368/2048b-rsa.zip)

**Comment by texadactyl** [comment]
How was this DER file generated?
How was it written to a disk file?


Erroneous DER file:

```
openssl asn1parse -inform DER -in *.der

    0:d=0  hl=4 l= 730 cons: SEQUENCE          
    4:d=1  hl=4 l= 579 cons: SEQUENCE          
    8:d=2  hl=2 l=   2 prim: INTEGER           :0DFC
   12:d=2  hl=2 l=  13 cons: SEQUENCE          
   14:d=3  hl=2 l=   9 prim: OBJECT            :sha1WithRSAEncryption
   25:d=3  hl=2 l=   0 prim: NULL              
   27:d=2  hl=3 l= 155 cons: SEQUENCE          
   30:d=3  hl=2 l=  11 cons: SET               
   32:d=4  hl=2 l=   9 cons: SEQUENCE          
   34:d=5  hl=2 l=   3 prim: OBJECT            :countryName
   39:d=5  hl=2 l=   2 prim: PRINTABLESTRING   :JP
   43:d=3  hl=2 l=  14 cons: SET               
   45:d=4  hl=2 l=  12 cons: SEQUENCE          
   47:d=5  hl=2 l=   3 prim: OBJECT            :stateOrProvinceName
   52:d=5  hl=2 l=   5 prim: PRINTABLESTRING   :Tokyo
   59:d=3  hl=2 l=  16 cons: SET               
   61:d=4  hl=2 l=  14 cons: SEQUENCE          
   63:d=5  hl=2 l=   3 prim: OBJECT            :localityName
   68:d=5  hl=2 l=   7 prim: PRINTABLESTRING   :Chuo-ku
   77:d=3  hl=2 l=  17 cons: SET               
   79:d=4  hl=2 l=  15 cons: SEQUENCE          
   81:d=5  hl=2 l=   3 prim: OBJECT            :organizationName
   86:d=5  hl=2 l=   8 prim: PRINTABLESTRING   :Frank4DD
   96:d=3  hl=2 l=  24 cons: SET               
   98:d=4  hl=2 l=  22 cons: SEQUENCE          
  100:d=5  hl=2 l=   3 prim: OBJECT            :organizationalUnitName
  105:d=5  hl=2 l=  15 prim: PRINTABLESTRING   :WebCert Support
  122:d=3  hl=2 l=  24 cons: SET               
  124:d=4  hl=2 l=  22 cons: SEQUENCE          
  126:d=5  hl=2 l=   3 prim: OBJECT            :commonName
  131:d=5  hl=2 l=  15 prim: PRINTABLESTRING   :Frank4DD Web CA
  148:d=3  hl=2 l=  35 cons: SET               
  150:d=4  hl=2 l=  33 cons: SEQUENCE          
  152:d=5  hl=2 l=   9 prim: OBJECT            :emailAddress
  163:d=5  hl=2 l=  20 prim: IA5STRING         :support@frank4dd.com
  185:d=2  hl=2 l=  30 cons: SEQUENCE          
  187:d=3  hl=2 l=  13 prim: UTCTIME           :120822052741Z
  202:d=3  hl=2 l=  13 prim: UTCTIME           :170821052741Z
  217:d=2  hl=2 l=  74 cons: SEQUENCE          
  219:d=3  hl=2 l=  11 cons: SET               
  221:d=4  hl=2 l=   9 cons: SEQUENCE          
  223:d=5  hl=2 l=   3 prim: OBJECT            :countryName
  228:d=5  hl=2 l=   2 prim: PRINTABLESTRING   :JP
  232:d=3  hl=2 l=  14 cons: SET               
  234:d=4  hl=2 l=  12 cons: SEQUENCE          
  236:d=5  hl=2 l=   3 prim: OBJECT            :stateOrProvinceName
  241:d=5  hl=2 l=   5 prim: UTF8STRING        :Tokyo
  248:d=3  hl=2 l=  17 cons: SET               
  250:d=4  hl=2 l=  15 cons: SEQUENCE          
  252:d=5  hl=2 l=   3 prim: OBJECT            :organizationName
  257:d=5  hl=2 l=   8 prim: UTF8STRING        :Frank4DD
  267:d=3  hl=2 l=  24 cons: SET               
  269:d=4  hl=2 l=  22 cons: SEQUENCE          
  271:d=5  hl=2 l=   3 prim: OBJECT            :commonName
  276:d=5  hl=2 l=  15 prim: UTF8STRING        :www.example.com
  293:d=2  hl=4 l= 290 cons: SEQUENCE          
  297:d=3  hl=2 l=  13 cons: SEQUENCE          
  299:d=4  hl=2 l=   9 prim: OBJECT            :rsaEncryption
  310:d=4  hl=2 l=   0 prim: NULL              
  312:d=3  hl=4 l= 271 prim: BIT STRING        
  587:d=1  hl=2 l=  13 cons: SEQUENCE          
  589:d=2  hl=2 l=   9 prim: OBJECT            :sha1WithRSAEncryption
  600:d=2  hl=2 l=   0 prim: NULL              
  602:d=1  hl=3 l= 129 prim: BIT STRING        
Error in encoding
140480459883840:error:0D07207B:asn1 encoding routines:ASN1_get_object:header too long:../crypto/asn1/asn1_lib.c:101:
```

**Comment by jsahil730** [comment]
It actually is part of a crypto challenge(a CTF), and I don't really know how it was prepared, but running the command `openssl x509 -text -noout -inform DER -in 2048b-rsa.der` prints out all the information correctly

**Comment by texadactyl** [comment]
Did you notice that this certificate has expired?

**Comment by texadactyl** [comment]
While step-debugging, I see decoding() returning these exceptions:
```
ValueError: Unexpected number of members (3) in the sequence
ValueError: Unexpected extra data after the DER structure
```
The last exception is related to my earlier observation running an ASN parse on the DER.

While ```openssl x509``` might cover up these anomalies in the interest of providing information, it does not mean that it is a valid certificate.

**Comment by texadactyl** [comment]
A little more detail in the ASN decoding:

```
Unexpected number of members in the sequence: [b'0\x82\x02C\x02\x02\r\xfc0\r\x06\t*\x86H\x86\xf7\r\x01\x01\x05\x05\x000\x81\x9b1\x0b0\t\x06\x03U\x04\x06\x13\x02JP1\x0e0\x0c\x06\x03U\x04\x08\x13\x05Tokyo1\x100\x0e\x06\x03U\x04\x07\x13\x07Chuo-ku1\x110\x0f\x06\x03U\x04\n\x13\x08Frank4DD1\x180\x16\x06\x03U\x04\x0b\x13\x0fWebCert Support1\x180\x16\x06\x03U\x04\x03\x13\x0fFrank4DD Web CA1#0!\x06\t*\x86H\x86\xf7\r\x01\t\x01\x16\x14support@frank4dd.com0\x1e\x17\r120822052741Z\x17\r170821052741Z0J1\x0b0\t\x06\x03U\x04\x06\x13\x02JP1\x0e0\x0c\x06\x03U\x04\x08\x0c\x05Tokyo1\x110\x0f\x06\x03U\x04\n\x0c\x08Frank4DD1\x180\x16\x06\x03U\x04\x03\x0c\x0fwww.example.com0\x82\x01"0\r\x06\t*\x86H\x86\xf7\r\x01\x01\x01\x05\x00\x03\x82\x01\x0f\x000\x82\x01\n\x02\x82\x01\x01\x00\xb4\xcf\xd1^3)\xec\x0b\xcf\xaev\xf5\xfe-\xc8\x99\xc6xy\xb9\x18\xf8\x0b\xd4\xba\xb4\xd7\x9e\x02R\x06\t\xf4\x18\x93L\xd4p\xd1B\xa0)\x13\x92sPw\xf6\x04\x89\xac\x03,\xd6\xf1\x06\xab\xadl\xc0\xd9\xd5\xa6\xab\xca\xcdZ\xd2V&Q\xe5K\x08\x8a\xaf\xcc\x19\x0f%4\x90\xb0*)A\x0fU\xf1k\x93\xdb\x9d\xb3\xcc\xdc\xec\xeb\xc7U\x18\xd7B%\xdeI5\x142\x92\x9c\x1e\xc6i\xe3<\xfb\xf4\x9a\xf8\xfb\x8b\xc5\xe0\x1b~\xfdO%\xba?\xe5\x96W\x9a$yI\x17\'\xd7\x89Kj.\r\x87Q\xd9#=\x06\x85V\xf8X1\x0e\xee\x81\x99xh\xcdnD~\xc9\xda\x8cZ{\x1c\xbf$@)H\xd1\x03\x9c\xef\xdc\xae*]\xf8\xf7j\xc7\xe9\xbc\xc5\xb0Y\xf6\x95\xfc\x16\xcb\xd8\x9c\xed\xc3\xfc\x12\x90\x93xZu\xb4V\x83\xfa\xfcA\x84\xf6dy45\x1c\xacz\x85\x0esxr\x01\xe7$\x89%\x9e\xda\x7fe\xbc\xaf\x87\x93\x19\x8c\xdbu\x15\xb6\xe00\xc7\x08\xf8Y\x02\x03\x01\x00\x01', 

b'0\r\x06\t*\x86H\x86\xf7\r\x01\x01\x05\x05\x00', 

b'\x03\x81\x81\x00@\xcb\xfe\x04[\xc6t\xc5s\x91\x06\x90\xdf\xff\xb6\x9e\x85s\xfe\xe0\no:D/\xccSs\x162?yd9\xe8x\x16\x8cbIj\xb2\xe6\x91\x85\x00\xb7O8\xda\x03\xb9\x81i.\x18\xc9I\x96\x84\xc2\xeb\xe3#\xf4\xeb\xachKWZQ\x1b\xd7\xeb\xc01l\x86\xa0\xf6U\xa8\xf8\x10\xd0B\x06\x1e\x94\xa5\xe0h\xa7\x9f\xb6\xf3\x9c\xd0\xe1";\xab\x85=\xa1\'\x9bP2b\xb8\xecz\xfa\xd6}+)\xe6\xad\xb2iM(\xb4\xf8\x13']

```
There are 3 members of the DER sequence being decoded while there is only supposed to be 2.  I suspect that the 3rd member is the extra that rubbish that ```openssl asn1parse``` complained about.

**Comment by texadactyl** [comment]
When one hexdumps that DER file, you can clearly see the 3rd sequence member at the end of the file.

**Comment by texadactyl** [comment]
Bottom line: it's incorrectly DER-encoded.

@Legrandin ?

@Legrandin By the way, "RSA key format not supported" is probably too generic.  It would be helpful if error messages were more specific.  Or, at the low-level routines, print error messages with more detail as to what is going wrong.

**Comment by texadactyl** [comment]
@jsahil730 For this challenge, do you need this specific certificate? Can you find another one or create one of your own?

**Comment by jsahil730** [comment]
Well yeah, this specific certificate needs to be decoded and the n value needs to be obtained. I was able to decode it using `load_der_x509_certificate` from `cryptography.x509`, just wanted to make sure that there were no issues with this library. Thanks for looking into this!

**Comment by texadactyl** [comment]
@jsahil730 - thanks for that reference to load_der_x509_certificate

**Comment by Legrandin** [comment]
Loading fails because the certificate is not correctly encoded with DER (as shown by @texadactyl), more specifically because of the 1 stray byte at the end. If you shorten the data by 1, it will load.

Failing is definitely the correct behavior in this case, but thanks for flagging.

**Comment by texadactyl** [comment]
Agreed.  I just hexedited out the last byte in the file and now RSA.import_key is happy.

Failing is the correct behavior but the unwitting user employing pycryptodome could use more specific guidance.  Besides providing self-help to the user, it might avoid some issue reports.
