### ISSUE TITLE
TypeError: Only byte strings can be passed to C code

### ISSUE THREAD

**Issue by CashCode** [Legrandin/pycryptodome#43]
Hey! I'm not strong in python, trying to run project on windows (on linux it was ok), but have problems with crypto library, I installed pycryptodome and got this error. Any way to fix it?
```
C:\Users\ext>python3 C:\Users\ext\Desktop\pc\lib\gui.py
Traceback (most recent call last):
  File "C:\Users\ext\Desktop\pc\lib\gui.py", line 201, in <module>
    main()
  File "C:\Users\ext\Desktop\pc\lib\gui.py", line 195, in main
    app = PyCoin(root)
  File "C:\Users\ext\Desktop\pc\lib\gui.py", line 33, in __init__
    self.initApp()
  File "C:\Users\ext\Desktop\pc\lib\gui.py", line 49, in initApp
    c = CoinBase(owner=KeyStore.getPrivateKey(), amt=100)
  File "C:\Users\ext\Desktop\pc\lib\TransactionManager\coinbase.py", line 37, in
 __init__
    self.add_output(out)
  File "C:\Users\ext\Desktop\pc\lib\TransactionManager\coinbase.py", line 58, in
 add_output
    output.transaction = self.hash_transaction()
  File "C:\Users\ext\Desktop\pc\lib\TransactionManager\transaction.py", line 123
, in hash_transaction
    self.hash.update(self.pack())
  File "E:\py3\lib\site-packages\Crypto\Hash\SHA256.py", line 96, in update
    expect_byte_string(data)
  File "E:\py3\lib\site-packages\Crypto\Util\_raw_api.py", line 172, in expect_b
yte_string
    raise TypeError("Only byte strings can be passed to C code")
TypeError: Only byte strings can be passed to C code
```

**Comment by Legrandin** [comment]
Well, the message says it all: in line  123 of *TransactionManager\transaction.py* you are trying to hash a piece of data (output of `self.pack()`) which is not a byte string.

I can't really tell where that code comes from so I can't help much...

**Comment by aghasoroush** [comment]
We had this problem. It's not compatible with PyCrypto. You need to convert it to byte string.
Here it is the solution we've used:
```python
byte_str = raw_string.unicode('utf8')
```
