### ISSUE TITLE
pycryptodome does not seem to handle special characters (non-alphanumeric)

### ISSUE THREAD

**Issue by andrijaperovic** [Legrandin/pycryptodome#525]
Encryption algorithm details
Algorithm – AES
Key Size – 352 Bits
Cyber Block – GCM
Encoding – UTF-8
Message Digest value: SHA-256
AES 32 bytes (+1 byte padding) key/ 12 byte nonce

During `decrypt_and_verify` stage, we are encountering an issue where special characters in the message (e.g. `@`) result in a MAC check failed: 
```
======================================================================
ERROR: test_decrypt 
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_security.py", line 38, in test_decrypt
    actual_output = decrypt("key", "iv", data)
  File "/usr/local/lib/python3.8/site-packages/scai_pignus/security.py", line 48, in decrypt
    decrypted = aes.decrypt_and_verify(base64.b64decode(data[0:12].encode('utf-8')), base64.b64decode(data[12:36].encode('utf-8')))
  File "/usr/local/lib/python3.8/site-packages/Cryptodome/Cipher/_mode_gcm.py", line 567, in decrypt_and_verify
    self.verify(received_mac_tag)
  File "/usr/local/lib/python3.8/site-packages/Cryptodome/Cipher/_mode_gcm.py", line 508, in verify
    raise ValueError("MAC check failed")
ValueError: MAC check failed
```

When decrypting an alphanumeric string without any special characters, the decryption happens without any issues:
```
Ran 2 tests in 0.003s

OK
```

The encrypt/decrypt implementation we are leveraging: 
```
def encrypt(key, iv, data):
    """
    Root encryption logic

    :param key: security key
    :type key:  str
    :param iv:  security iv
    :type iv:   str
    :param data:    String to be encrypted
    :type data: str
    :return:    encrypted data
    :rtype: str
    """
    aes = AES.new(base64.b64decode(key), AES.MODE_GCM, nonce=base64.b64decode(iv))
    ciphertext, tag = aes.encrypt_and_digest(data.encode('utf-8'))
    return base64.b64encode(ciphertext+tag).decode('utf-8')

def decrypt(key, iv, data):
    """
    Root decryption logic

    :param key: security key
    :type key:  str
    :param iv:  security iv
    :type iv:   str
    :param data:    String to be encrypted
    :type data: str
    :return: decrypted data
    :rtype: str
    """
    aes = AES.new(base64.b64decode(key), AES.MODE_GCM, nonce=base64.b64decode(iv))
    decrypted = aes.decrypt_and_verify(base64.b64decode(data[0:12].encode('utf-8')), base64.b64decode(data[12:36].encode('utf-8')))
    return decrypted.decode('utf-8')
```

Are the `ciphertext` and `mac_tag` correct here in terms of how the `data` variable is being split? 
Also do we need to specify a `mac_len` when initializing the `AES` constructor?

**Comment by Varbin** [comment]
@andrijaperovic 

It is not required to set `mac_tag` explicitly. When not setting it, the default one (16 bytes) is used. 

I would suggest splitting the the ciphertext *after* base64 decoding. The below code works for any kind of data with any length:

```python3
from Crypto.Cipher import AES
import base64

import secrets


def encrypt(key, iv, data):
    """
    Root encryption logic

    :param key: security key
    :type key:  str
    :param iv:  security iv
    :type iv:   str
    :param data:    String to be encrypted
    :type data: str
    :return:    encrypted data
    :rtype: str
    """
    aes = AES.new(base64.b64decode(key), AES.MODE_GCM, nonce=base64.b64decode(iv))
    ciphertext, tag = aes.encrypt_and_digest(data.encode('utf-8'))
    return base64.b64encode(ciphertext+tag).decode('utf-8')

def decrypt(key, iv, data):
    """
    Root decryption logic

    :param key: security key
    :type key:  str
    :param iv:  security iv
    :type iv:   str
    :param data:    String to be decrypted
    :type data: str
    :return: decrypted data
    :rtype: str
    """
    aes = AES.new(base64.b64decode(key), AES.MODE_GCM, nonce=base64.b64decode(iv))
    decoded = base64.b64decode(data)
    decrypted = aes.decrypt_and_verify(decoded[:-16], decoded[-16:])
    return decrypted.decode('utf-8')


if __name__ == "__main__":
    import random
    import secrets

    key = 'Pwti+Im4u/ekCUzEhmmhi3sn1NKFD/R1XT0KLEuFe4g='

    # Be sure to use an unique nonce for every call to encrypt()!  
    nonce = base64.b64encode(secrets.token_bytes(12))
    # Random plaintext to show it works with any data, even with multibyte characters
    random_plaintext = ''.join((chr(random.randint(0, 2048)) for i in range(random.randint(5, 973))))

    cipher_text = encrypt(key, nonce, random_plaintext)
    if decrypt(key, nonce, cipher_text) == random_plaintext:
        print("OK")
    else:
        print("This did not work.")
```
