### ISSUE TITLE
OSError: Cannot load native module 'Crypto.Hash._keccak': Not found '_keccak.cpython-310-x86_64-linux-gnu.so'

### ISSUE THREAD

**Issue by ThomasDalla** [Legrandin/pycryptodome#594]
Python 3.10 (same with 3.9), latest Manjaro, kernel 5.10.

```
  File "/project/venv/lib/python3.10/site-packages/Crypto/Hash/keccak.py", line 39, in <module>
    _raw_keccak_lib = load_pycryptodome_raw_lib("Crypto.Hash._keccak",
  File "/project/venv/lib/python3.10/site-packages/Crypto/Util/_raw_api.py", line 309, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Hash._keccak': Not found '_keccak.cpython-310-x86_64-linux-gnu.so', Cannot load '_keccak.abi3.so': /project/venv/lib/python3.10/site-packages/Crypto/Util/../Hash/_keccak.abi3.so: failed to map segment from shared object, Not found '_keccak.so'
```

**Comment by Legrandin** [comment]
I cannot reproduce this:
```
[root@03642cde0751 mnt]# cat /etc/lsb-release 
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.2.2
DISTRIB_CODENAME=Qonos
DISTRIB_DESCRIPTION="Manjaro Linux"

[root@03642cde0751 mnt]# uname -a
Linux 03642cde0751 5.15.8-200.fc35.x86_64 #1 SMP Tue Dec 14 14:26:01 UTC 2021 x86_64 GNU/Linux

[root@03642cde0751 mnt]# python --version
Python 3.10.1

[root@03642cde0751 mnt]# python -m venv venv

[root@03642cde0751 mnt]# . venv/bin/activate
(venv) [root@03642cde0751 mnt]# pip install pycryptodome
Collecting pycryptodome
  Downloading pycryptodome-3.14.0-cp35-abi3-manylinux2010_x86_64.whl (2.0 MB)
     |████████████████████████████████| 2.0 MB 4.3 MB/s 
Installing collected packages: pycryptodome
Successfully installed pycryptodome-3.14.0
WARNING: You are using pip version 21.2.4; however, version 22.0 is available.
You should consider upgrading via the '/mnt/venv/bin/python -m pip install --upgrade pip' command.

(venv) [root@03642cde0751 mnt]# python
Python 3.10.1 (main, Dec 18 2021, 23:53:45) [GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from Crypto.Hash import keccak
>>> keccak.new(data=b'XYZ', digest_bits=512).hexdigest()
'13e0b2fca04643825bade96d72ffbd50da4890d73af85c6ae1c787370f4aa99f502b9d91f4d409f2c73906e01228e75f2510a75cd316834c28af08135c924755'
>>> 
```

**Comment by ThomasDalla** [comment]
Not sure what's  wrong with my install... The only difference is my kernel version (5.10, the "recommended" one) but I installed and tested on 5.15 (yours) and 5.16 (latest available) with the same results.

```
 cat /etc/lsb-release                                   
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.2.2
DISTRIB_CODENAME=Qonos
DISTRIB_DESCRIPTION="Manjaro Linux"
```

```
 uname -a
Linux yoga 5.10.93-1-MANJARO #1 SMP PREEMPT Thu Jan 20 09:46:07 UTC 2022 x86_64 GNU/Linux
```

Python import:
```
 . venv/bin/activate
(venv)  username@yoga  /project  python              
Python 3.10.1 (main, Dec 18 2021, 23:53:45) [GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from Crypto.Hash import keccak
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/project/venv/lib/python3.10/site-packages/Crypto/Hash/keccak.py", line 39, in <module>
    _raw_keccak_lib = load_pycryptodome_raw_lib("Crypto.Hash._keccak",
  File "/project/venv/lib/python3.10/site-packages/Crypto/Util/_raw_api.py", line 309, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Hash._keccak': Not found '_keccak.cpython-310-x86_64-linux-gnu.so', Cannot load '_keccak.abi3.so': /project/venv/lib/python3.10/site-packages/Crypto/Util/../Hash/_keccak.abi3.so: failed to map segment from shared object, Not found '_keccak.so'
>>> 
```

`_keccak.abi3.so` is there and is executable:
```
ll venv/lib/python3.10/site-packages/Crypto/Util/../Hash/_kecc*
.rwxr-xr-x@ 35k username group 27 Jan 09:16  venv/lib/python3.10/site-packages/Crypto/Util/../Hash/_keccak.abi3.so
```

But your question made me remember that `/project` comes from a NFS share (from a Fedora box).
So I tried the same from a local folder instead and... it works!

Not sure why it fails from the remote folder (think it was working before), but that seems to be the issue.
Closing the ticket. Thanks for the help!
