### ISSUE TITLE
Failing on M1 Mac - OSError: Cannot load native module 'Crypto.Hash._SHA256'

### ISSUE THREAD

**Issue by krisun09** [Legrandin/pycryptodome#615]
I am trying to follow the installation guide for [PyCryptodome](https://www.pycryptodome.org/en/latest/src/installation.html). But when I try to run Cryptodome / Crypto modules in my code it is giving me the following error. 

![image](https://user-images.githubusercontent.com/84257752/163662627-311e34e0-4a56-40eb-bc7a-8d23e1d766ea.png)

With python3.9, I've tried installing pycryptodome 3.14.1, removing pycryptodome 3.14.1 then install pycryptodomex 3.14.1, removing pycryptodome x3.14.1 then install pycryptodome 3.10.1, 

Then I tried to update my python to python3.10 using ARM, and install pycryptodome 3.14.1, which is still giving me the same error. 
<img width="1239" alt="image" src="https://user-images.githubusercontent.com/84257752/163662497-af26a716-418e-4846-9ddd-cf9cdf51f17a.png">

Should I try reinstalling python? ;( Any help is appreciated. Thanks in advance.

**Comment by Varbin** [comment]
As I do not have an ARM Mac (or any Mac at all), I can only be of little help. 

The error message indicates the compiled extensions and your Python installation have different architectures. Do you mind telling which architecture your Python and the installed extension has? You should be able to get it with `file /opt/homebrew/lib/python3.10/site-packages/Crypto/Hash/_SHA256.abi3.so` and `file $(which python3)`.

**Comment by Will-Gaines** [comment]
> As I do not have an ARM Mac (or any Mac at all), I can only be of little help.
> 
> The error message indicates the compiled extensions and your Python installation have different architectures. Do you mind telling which architecture your Python and the installed extension has? You should be able to get it with `file /opt/homebrew/lib/python3.10/site-packages/Crypto/Hash/_SHA256.abi3.so` and `file $(which python3)`.

I am having a near identical issue (but failing to import _raw_ecb native module). PyCryptoDome was installed as part of other project dependencies (using Poetry over pip), and have the same errors coming back as the OP.

Outputs of your suggested commands:
`file /Users/XXXX/environments/grid-actions/lib/python3.9/site-packages/Cryptodome/Cipher/_raw_ecb.abi3.so `

`/Users/XXXX/environments/grid-actions/lib/python3.9/site-packages/Cryptodome/Cipher/_raw_ecb.abi3.so: Mach-O 64-bit bundle x86_64`

`file $(which python3)`  (Run inside my virtualenv)                        
`/Users/william.gaines/environments/grid-actions/bin/python3: Mach-O 64-bit executable arm64`

**Comment by xilopaint** [comment]
Some users of my application are complaining about the same problem. @Legrandin, I think this issue should be reopened.

**Comment by j1nma** [comment]
I also have this problem with Python 3.8.12, Poetry, on Apple M1

**Comment by Luke7389** [comment]
same problem here, python 3.10

**Comment by Luke7389** [comment]
resolved by downgrading to python 3.9, in my case I was using a function that uses a module called pyteal, downgrading forced me to use a different version of petal and now everything works as expected

**Comment by xilopaint** [comment]
> resolved by downgrading to python 3.9

This is the traceback from one of them:

```
ERROR: Alfred PDF Tools[Run Script] Traceback (most recent call last):
  File "/Users/xyz/Downloads/Alfred.alfredpreferences/workflows/user.workflow.F5626124-7D80-45A1-A349-E413ADB69042/alfred_pdf_tools.py", line 48, in <module>
    from PyPDF2 import PdfReader, PdfWriter, PdfMerger, PageRange, PageObject, errors
  File "/Users/xyz/Downloads/Alfred.alfredpreferences/workflows/user.workflow.F5626124-7D80-45A1-A349-E413ADB69042/PyPDF2/__init__.py", line 10, in <module>
    from ._encryption import PasswordType
  File "/Users/xyz/Downloads/Alfred.alfredpreferences/workflows/user.workflow.F5626124-7D80-45A1-A349-E413ADB69042/PyPDF2/_encryption.py", line 60, in <module>
    from Crypto.Cipher import AES, ARC4  # type: ignore[import]
  File "/Users/xyz/Downloads/Alfred.alfredpreferences/workflows/user.workflow.F5626124-7D80-45A1-A349-E413ADB69042/Crypto/Cipher/__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "/Users/xyz/Downloads/Alfred.alfredpreferences/workflows/user.workflow.F5626124-7D80-45A1-A349-E413ADB69042/Crypto/Cipher/_mode_ecb.py", line 35, in <module>
    raw_ecb_lib = load_pycryptodome_raw_lib("Crypto.Cipher._raw_ecb", """
  File "/Users/xyz/Downloads/Alfred.alfredpreferences/workflows/user.workflow.F5626124-7D80-45A1-A349-E413ADB69042/Crypto/Util/_raw_api.py", line 309, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Not found '_raw_ecb.cpython-39-darwin.so', Cannot load '_raw_ecb.abi3.so': dlopen(/Users/xyz/Downloads/Alfred.alfredpreferences/workflows/user.workflow.F5626124-7D80-45A1-A349-E413ADB69042/Crypto/Util/../Cipher/_raw_ecb.abi3.so, 0x0006): tried: '/Users/xyz/Downloads/Alfred.alfredpreferences/workflows/user.workflow.F5626124-7D80-45A1-A349-E413ADB69042/Crypto/Util/../Cipher/_raw_ecb.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/Users/xyz/Downloads/Alfred.alfredpreferences/workflows/user.workflow.F5626124-7D80-45A1-A349-E413ADB69042/Crypto/Cipher/_raw_ecb.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), Not found '_raw_ecb.so'
```

**Comment by Luke7389** [comment]
@xilopaint although they might be related, you are now receiving a different error, which looks like the one Will is receiving, in my case it worked simply downgrading. I used a clean python installation

**Comment by pyrito** [comment]
Hi, I'm currently running into this issue myself. Is there a clear idea on why the x86 shared object is being installed instead of the arm64 one? Is there a way to force the install to use the arm64 version? @Legrandin your help would be much appreciated here!

**Comment by jeugregg** [comment]
Hi, I have the same error. 
For you investigation, I managed to use 3.15.0 version with conda from a fresh new env : 
`pip uninstall pycryptodome`(v3.16.0)
`conda install pycryptodome` (v3.15.0)
It was not the last version... why?

**Comment by Rikuto7** [comment]
I am also having the same problem.
I get an error in lambda.
I installed the following.
I also tried using docker with amazonlinux:latest but it does not work.
`docker run -v "$PWD":/var/task "public.ecr.aws/sam/build-python3.9" /bin/sh -c "pip install -r requirements.txt -t python/lib/python3.9/site-packages/; exit"`

`Cannot load native module 'Crypto.Cipher._raw_ecb': Not found '_raw_ecb.cpython-39-x86_64-linux-gnu.so', Cannot load '_raw_ecb.abi3.so': /opt/python/lib/python3.9/site-packages/Crypto/Util/../Cipher/_raw_ecb.abi3.so: cannot open shared object file: No such file or directory, Not found '_raw_ecb.so'`

Does anyone know anything about this?

**Comment by EnkhAmar** [comment]
I have same issue here. I am trying to make layer for aws sam project. I am using macbook m1.
"Cannot load native module 'Crypto.Hash._MD5': Not found '_MD5.cpython-39-aarch64-linux-gnu.so', Cannot load '_MD5.abi3.so': /opt/python/Crypto/Util/../Hash/_MD5.abi3.so: invalid ELF header, Not found '_MD5.so'"

**Comment by gorosz** [comment]
I also have the same problem as @Rikuto7 . I have an application which depends on pycryptodome and I try to run it in a docker container. 
I use ubuntu focal as the base of my docker image. 
I install pycryptodome with apt. Once I start my application I get the following error:
```
from Cryptodome.Hash import MD4
  File "/usr/lib/python3/dist-packages/Cryptodome/Hash/MD4.py", line 54, in <module>
    _raw_md4_lib = load_pycryptodome_raw_lib(
  File "/usr/lib/python3/dist-packages/Cryptodome/Util/_raw_api.py", line 259, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Cryptodome.Hash._MD4': 
```
What I figured out is that when pycryptodome tries to collect the C file extensions suffixes the .cpython-38-x86_64-linux-gnu.so suffix is not showing up.

This is the 3.6.1 pycryptodome part which handles the lib loading:
```
if sys.version_info[0] <= 3 or \
   (sys.version_info[0] == 3 and sys.version_info[1] <= 3):

    import imp
    extension_suffixes = []
    for ext, mod, typ in imp.get_suffixes():
        if typ == imp.C_EXTENSION:
            extension_suffixes.append(ext)

else:
    from importlib import machinery
    extension_suffixes = machinery.EXTENSION_SUFFIXES

```
It doesn't matter which branch get executed the  .cpython-38-x86_64-linux-gnu.so extension suffix is missing, although when I start the interpreter and run imp.get_suffixes() or machinery.EXTENSION_SUFFIXES the suffixes is there.

When I modify the lib and include the suffix in the initial extension_suffixes or append to it the .so get loaded fine

I don't know if the two cases (docker, Mac M1) is related but very similar.
I also know that my lib version a bit out dated but I have strict version rules and cannot update but the lib loading logic hasn't changed that much as I can see.


python version is 3.8.10
pycryptodome is 3.6.1

**Comment by BastianMuc** [comment]
I'm seeing a related issue with PyCryptodome 3.23.0, Python 3.11.2, running in a VM container under Alpine Linux (musl).


Sep 05 00:25:30:     from Crypto.Hash import SHA256
Sep 05 00:25:30:   File "/opt/packages/Crypto/Hash/SHA256.py", line 29, in <module>
Sep 05 00:25:30:     _raw_sha256_lib = load_pycryptodome_raw_lib("Crypto.Hash._SHA256",
Sep 05 00:25:30:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 05 00:25:30:   File "/opt/packages/Crypto/Util/_raw_api.py", line 315, in load_pycryptodome_raw_lib
Sep 05 00:25:30:     raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
Sep 05 00:25:30: OSError: Cannot load native module 'Crypto.Hash._SHA256': Not found '_SHA256.cpython-311-x86_64-linux-gnu.so', Cannot load '_SHA256.abi3.so': /opt/packages/Crypto/Util/../Hash/_SHA256.abi3.so: cannot open shared object file: No such file or directory, Not found '_SHA256.so'


I've made sure to build the package under Alpine as well to avoid architecture differences - did not help, unfortunately.

As I couldn't resolve this, I've reverted to a different library (hashlib) as a workaround.
