### ISSUE TITLE
[Help] - ValueError: Incorrect decryption.

### ISSUE THREAD

**Issue by andreabisello** [Legrandin/pycryptodome#675]
Please try this code in python 3.10 on Windows11 full updated with pycryptodome 3.15.0

 ```

import base64
from Crypto.PublicKey import RSA
from Crypto.Cipher import PKCS1_OAEP

my_private_key = "MIIEuwIBADANBgkqhkiG9w0BAQEFAASCBKUwggShAgEAAoIBAQCMNcRs7l3c5PuqUwCAXIJ6uWtz25V03196sd2tys0kWcfwILOVWEYNiovVWEf0IkrxkJi+X77PfL0lEetR/IEBKwUbyBgSGhCp7b6ovil97xHhGrkV4hU6S+/CWfb4lcCk1mEA58q1hdOMhOPrXt9JU2f8mhsEppkWXOd97zIqoA1y2CrlTqfBQ1UuYdYq0FAfT5gjzmYEjeqe9h0feFXiybDqDtmI2lLK4CTfEiJJU8ZIkTJuPH4b0R+CedLwuV+xPZ4VER0oJR4rsjGuV/8ci8nCP5v66ZmjZd6lrrTB7Aaqfh9PjLEmegcZju252BQhihGINo3pVUoq+NZ7kj1NAgMBAAECggEAL79HqwjpsgXQpkopy4y1anGmZAgNN4WyEChuI3cCsTRZ4C5iuaMcCBR8ViUAK+VZvDXPrlUQt7v09aDKkFr625j43mMfv1pc/mFWIkTQAHDfl9bv3MHnFLkzZu4YKsNknT3cPuCwqWxvhFTlAQyH4YKj0OPx+314eKMeukYwwU7KoGVV9/g/qFaIW530goRxhaHlNWdEhaH/9+6GWO2k9xri51i7gdSEB4yhq0XSceUf8NSsXUb2IawLc88NmFbW5WHezO2sax7A3eiJbSPDzZG5CPloZ6uOxr92kaNm+QkSgEjAip/NX1gnUILb766OozQwaBQ/Nw+yWcijxP4iyQKBgQDMHLuXmnsTK+dr8LkuIB89ixOCrX3UusjGguncQKPw8N9wSBxTraSgbqi+9G5VRlc+lSm50DbZogrzSXTzCqM7yG1TigSMGzikr+7qrjKWqfHlyxqSrwrvqGgf+O7dfyHNA3N7WM//aKYz/3DIhHRIhhzzzt3u7ZKC8qH44LHjBwKBgQCv2mP8pVmD1GYoZWOl5x88Qx8fW5sUxr9RjoS2y0ivIMM04lMGwYnSzFhT3O1I1AIJr4sEJVBG2H75Oe5OsD0aYuXDERDRdcYvmv4VRJa58TIZEOzoELR+OmuvwBytNG2j4JYiz/xPYTg1GVAVQh3SPWduYcW8szvGxGgNvVukCwJ/O8wvKTsY04UJR5Y+qkS+4kjcbmxlcO1H5OB1oxFM9kmbLEn0Ao/cqyPATDFQIat549vPXaCicSAIFT5wBMQZDmqpnM/ShTl0XsssM5TVPU6Mj8XxAwhFK/EqkDNdx4Z3YJiiPIDIbws5pgIwCI7FgnnIAaWZX2Y6hiKPUVqCwwKBgCAHBm7dLpBz/qcc0ClHDslK8EAlzvjZub6A1mr0WyiKLwNStQxl81QRI4Uil5TMCBL7hbYblaNRis6ZXm22a2qC2JXOZeHAMXg6Ikx9UXZMF3O5QWyCnlzfBv3bX12sTsup+64bcziB3FrPYWZ9xDCmPlA8Pmc/vYNWAh1+f1JBAoGBAL5bfW2GItaAfmKV4/tZhRApEZy9cnS7lNG+EdgJ2MUpQ96AJF1dq/hD8xMWhhQDWqzqklTC3bq5CBWSy+FfGnO2hoTKJPDUiuVqqtaWUHWcPCLgrJ8JRenM7GOzY1gpDfCwt7IJvljsr9Ozq7gr56nV/lsr/62po63ImC1JHhz4"

my_private_key_bytes = base64.b64decode(my_private_key)
rsa_key = RSA.importKey(my_private_key_bytes)

key = "QoRHPgai9VCaDfre9HfERgtF6p/EycuonShjImM/wAu3ufIgW/2y3iz74i0I0cZecbMaXycRVM1DYRmbdwO8W5gK/5IF8O4fRo/l/cwz+pE+2k0ZQy0o1rRT1lyTbLuN/+CKFgjuv3d1F5TL0la/+O8LRI2G3qgmuwV/RMhE/o7MgxSN3v4TDD/uw1odopblfrL3KA+Yh/QMNZZTbrPXuvhy67VLfQxHX1WbFyv52zZz+NOrjJtETC7+b3meHt9P7bfN7kRMBUPRHIAMovSE2GO0qq+83HLA2iAi3O8tJ8kV3gnQFr9i6B1gV/sGFLFMcZ52if9wjWpC+iqqntUd8w=="

key_bytes = base64.b64decode(key)


rsa_key = RSA.importKey(my_private_key_bytes)
cipher = PKCS1_OAEP.new(rsa_key)
decrypted = cipher.decrypt(key_bytes)


```

it obtains

```

Traceback (most recent call last):
  File "C:\src\qa-lsd-webservices\decryptrsa.py", line 17, in <module>
	decrypted = cipher.decrypt(key_bytes)
  File "C:\Users\andreabisello\AppData\Local\Programs\Python\Python310\lib\site-packages\Crypto\Cipher\PKCS1_OAEP.py", line 200, in decrypt
	raise ValueError("Incorrect decryption.")
ValueError: Incorrect decryption.

```

- rsa_key should be ok because i can generate the public key i already have with the rsa key
- the cipyer it simply one row of code
- the key to be decrypted is provided from another environment in witch it can be decrypted by c# so it should be ok.

any suggestion please?

**Comment by Akuli** [comment]
Your RSA key seems to be ok. It can be used to encrypt and decrypt data, e.g. this works:

```python
import base64
from Crypto.PublicKey import RSA
from Crypto.Cipher import PKCS1_OAEP

my_private_key = "MIIEuwIBADANBgkqhkiG9w0BAQEFAASCBKUwggShAgEAAoIBAQCMNcRs7l3c5PuqUwCAXIJ6uWtz25V03196sd2tys0kWcfwILOVWEYNiovVWEf0IkrxkJi+X77PfL0lEetR/IEBKwUbyBgSGhCp7b6ovil97xHhGrkV4hU6S+/CWfb4lcCk1mEA58q1hdOMhOPrXt9JU2f8mhsEppkWXOd97zIqoA1y2CrlTqfBQ1UuYdYq0FAfT5gjzmYEjeqe9h0feFXiybDqDtmI2lLK4CTfEiJJU8ZIkTJuPH4b0R+CedLwuV+xPZ4VER0oJR4rsjGuV/8ci8nCP5v66ZmjZd6lrrTB7Aaqfh9PjLEmegcZju252BQhihGINo3pVUoq+NZ7kj1NAgMBAAECggEAL79HqwjpsgXQpkopy4y1anGmZAgNN4WyEChuI3cCsTRZ4C5iuaMcCBR8ViUAK+VZvDXPrlUQt7v09aDKkFr625j43mMfv1pc/mFWIkTQAHDfl9bv3MHnFLkzZu4YKsNknT3cPuCwqWxvhFTlAQyH4YKj0OPx+314eKMeukYwwU7KoGVV9/g/qFaIW530goRxhaHlNWdEhaH/9+6GWO2k9xri51i7gdSEB4yhq0XSceUf8NSsXUb2IawLc88NmFbW5WHezO2sax7A3eiJbSPDzZG5CPloZ6uOxr92kaNm+QkSgEjAip/NX1gnUILb766OozQwaBQ/Nw+yWcijxP4iyQKBgQDMHLuXmnsTK+dr8LkuIB89ixOCrX3UusjGguncQKPw8N9wSBxTraSgbqi+9G5VRlc+lSm50DbZogrzSXTzCqM7yG1TigSMGzikr+7qrjKWqfHlyxqSrwrvqGgf+O7dfyHNA3N7WM//aKYz/3DIhHRIhhzzzt3u7ZKC8qH44LHjBwKBgQCv2mP8pVmD1GYoZWOl5x88Qx8fW5sUxr9RjoS2y0ivIMM04lMGwYnSzFhT3O1I1AIJr4sEJVBG2H75Oe5OsD0aYuXDERDRdcYvmv4VRJa58TIZEOzoELR+OmuvwBytNG2j4JYiz/xPYTg1GVAVQh3SPWduYcW8szvGxGgNvVukCwJ/O8wvKTsY04UJR5Y+qkS+4kjcbmxlcO1H5OB1oxFM9kmbLEn0Ao/cqyPATDFQIat549vPXaCicSAIFT5wBMQZDmqpnM/ShTl0XsssM5TVPU6Mj8XxAwhFK/EqkDNdx4Z3YJiiPIDIbws5pgIwCI7FgnnIAaWZX2Y6hiKPUVqCwwKBgCAHBm7dLpBz/qcc0ClHDslK8EAlzvjZub6A1mr0WyiKLwNStQxl81QRI4Uil5TMCBL7hbYblaNRis6ZXm22a2qC2JXOZeHAMXg6Ikx9UXZMF3O5QWyCnlzfBv3bX12sTsup+64bcziB3FrPYWZ9xDCmPlA8Pmc/vYNWAh1+f1JBAoGBAL5bfW2GItaAfmKV4/tZhRApEZy9cnS7lNG+EdgJ2MUpQ96AJF1dq/hD8xMWhhQDWqzqklTC3bq5CBWSy+FfGnO2hoTKJPDUiuVqqtaWUHWcPCLgrJ8JRenM7GOzY1gpDfCwt7IJvljsr9Ozq7gr56nV/lsr/62po63ImC1JHhz4"
rsa_key = RSA.importKey(base64.b64decode(my_private_key))
encrypted = PKCS1_OAEP.new(rsa_key).encrypt(b"test asdasd")
print(PKCS1_OAEP.new(rsa_key).decrypt(encrypted))
```

How did you create the `key` variable (which is actually encrypted data, not a key)?

**Comment by andreabisello** [comment]
@Akuli  thanks for your help.
my_private_key is the b64 version of the encryption key used in a myxed encryption:
i send my public key to the server,
it returns to me the key,
i decrypt the key with my private key,
and i use the decrypted key to decrypt another string crypted in AES.

the key returned by the server should be OK because already used in c# software

**Comment by Akuli** [comment]
You need to know how the server encrypts. It's not just PKCS#1 OAEP.

**Comment by andreabisello** [comment]
@Akuli  waiting for developer answer ...

**Comment by Legrandin** [comment]
As far as I can tell, you are using the wrong algorithm.
You key (all zeroes) is encrypted with https://www.pycryptodome.org/src/cipher/pkcs1_v1_5, not OAEP.
