### ISSUE TITLE
Import not working in Python3.11

### ISSUE THREAD

**Issue by thibaut-probst** [Legrandin/pycryptodome#708]
I am running MacOS 10.15.7. I installed Python 3.11 and then PyCryptodome with the following command:
```
$ pip3.11 install pycryptodome
Collecting pycryptodome
  Using cached pycryptodome-3.17-cp35-abi3-macosx_10_9_x86_64.whl (1.6 MB)
Installing collected packages: pycryptodome
Successfully installed pycryptodome-3.17
```

However, the import is not working with "Crypto" but working with "crypto" (but not for internal modules, as show below):
```
>>> import Crypto
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'Crypto'
>>> import crypto
>>> from crypto.Hash import SHA224
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/crypto/Hash/SHA224.py", line 21, in <module>
    from Crypto.Util.py3compat import bord
ModuleNotFoundError: No module named 'Crypto'
```

Can you please provide some feedback? Thanks in advance!

**Comment by thibaut-probst** [comment]
I solved the issue by running:
```
$ pip3.11 list | grep crypt
crypto             1.4.1
pycryptodome       3.17
pycryptodomex      3.17
```
Then removing all these modules:
```
$ pip3.11 uninstall crypto
$ pip3.11 uninstall pycryptodome
$ pip3.11 uninstall pycryptodomex
```
And then reinstalling pycryptodome:
```
$ pip3.11 install pycryptodome
```

**Comment by jasonbu** [comment]
> crypto

same issue and conflict by module crypto
