### ISSUE TITLE
3.17.0: documentation buld fails wih latest sphinx

### ISSUE THREAD

**Issue by kloczek** [Legrandin/pycryptodome#713]
Looks like documentation build fails with latest `sphinx` 6.1.3
<details>

```console
+ /usr/bin/sphinx-build -n -T -b man Doc build/sphinx/man
Running Sphinx v6.1.3

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 351, in eval_config_file
    exec(code, namespace)  # NoQA: S102
  File "/home/tkloczko/rpmbuild/BUILD/pycryptodome-3.17.0/Doc/conf.py", line 82, in <module>
    version = release = "%d.%d" % version_tuple[:-1]
TypeError: not enough arguments for format string

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 279, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 202, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 173, in read
    namespace = eval_config_file(filename, tags)
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 364, in eval_config_file
    raise ConfigError(msg % traceback.format_exc()) from exc
sphinx.errors.ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 351, in eval_config_file
    exec(code, namespace)  # NoQA: S102
  File "/home/tkloczko/rpmbuild/BUILD/pycryptodome-3.17.0/Doc/conf.py", line 82, in <module>
    version = release = "%d.%d" % version_tuple[:-1]
TypeError: not enough arguments for format string


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 351, in eval_config_file
    exec(code, namespace)  # NoQA: S102
  File "/home/tkloczko/rpmbuild/BUILD/pycryptodome-3.17.0/Doc/conf.py", line 82, in <module>
    version = release = "%d.%d" % version_tuple[:-1]
TypeError: not enough arguments for format string

['/home/tkloczko/rpmbuild/BUILD/pycryptodome-3.17.0/lib', '/usr/bin', '/usr/lib64/python38.zip', '/usr/lib64/python3.8', '/usr/lib64/python3.8/lib-dynload', '/usr/lib64/python3.8/site-packa
ges', '/usr/lib/python3.8/site-packages']
```
</details>

**Comment by Legrandin** [comment]
Duplicated of https://github.com/Legrandin/pycryptodome/issues/730
