### ISSUE TITLE
load_pycryptodome_raw_lib fails when using zipapp

### ISSUE THREAD

**Issue by remyroy** [Legrandin/pycryptodome#743]
> Using the [zipapp](https://docs.python.org/3/library/zipapp.html#module-zipapp) module, it is possible to create self-contained Python programs, which can be distributed to end users who only need to have a suitable version of Python installed on their system. The key to doing this is to bundle all of the application’s dependencies into the archive, along with the application code.

When bundling an application that depends on PyCryptodome using zipapp, `load_pycryptodome_raw_lib` fails to load shared libraries.

Here is an output from such a try:

```
Uncaught exception
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Test\Projects\eth-wizard\dist\ethwizard-0.9.5-rc.9-win.pyz\__main__.py", line 4, in <module>
    wizard.run()
  File "C:\Users\Test\Projects\eth-wizard\dist\ethwizard-0.9.5-rc.9-win.pyz\ethwizard\wizard.py", line 44, in run
    steps = get_install_steps(platform)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Test\Projects\eth-wizard\dist\ethwizard-0.9.5-rc.9-win.pyz\ethwizard\platforms\__init__.py", line 140, in get_install_steps
    from ethwizard.platforms.windows.install import installation_steps as windows10_steps
  File "C:\Users\Test\Projects\eth-wizard\dist\ethwizard-0.9.5-rc.9-win.pyz\ethwizard\platforms\windows\install.py", line 67, in <module>
    from ethwizard.utils.keystore import Keystore
  File "C:\Users\Test\Projects\eth-wizard\dist\ethwizard-0.9.5-rc.9-win.pyz\ethwizard\utils\keystore.py", line 14, in <module>
    from Crypto.Hash import (
  File "C:\Users\Test\Projects\eth-wizard\dist\ethwizard-0.9.5-rc.9-win.pyz\Crypto\Hash\SHA256.py", line 29, in <module>
    _raw_sha256_lib = load_pycryptodome_raw_lib("Crypto.Hash._SHA256",
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Test\Projects\eth-wizard\dist\ethwizard-0.9.5-rc.9-win.pyz\Crypto\Util\_raw_api.py", line 309, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Hash._SHA256': Not found '_SHA256.cp311-win_amd64.pyd', Not found '_SHA256.pyd'
```

**Comment by remyroy** [comment]
This is on Windows 10, using Python 3.11.3 (amd64) with `pycryptodome==3.18.0`
