### ISSUE TITLE
Very simple encryption-decryption fails randomly

### ISSUE THREAD

**Issue by ml-kalju** [Legrandin/pycryptodome#753]
I have tried to create AES encryption very much according to the examples in the documentation. How ever I randomly run into issues on the verification part of the `decrypt_and_verify()` method in my unit tests. I'm using Python 3.10 docker image with Gitlab CI and PyCryptodome version of 3.18.0. 

I have simple unit test that is failing randomly in my CI pipeline. I cannot find any reason why this is happening, but I'm not very experienced in cryptography. I'm not sure if this issue is mine or yours but some help would be very appreciated as I cannot find anything wrong with my code. The input file is written in the test's `setUp()` method and doesn't change between failed and successful tests.

Any help about this issue would be greatly appreciated!

The unit test is as follows:

<details>
  <summary>Unit test</summary>

``` python
import os
from pathlib import Path
import unittest
import filecmp

import util.crypting

INPUT_FILE_NAME = Path("input_test_file")
ENCRYPTED_FILE_NAME = Path("encrypted_test_file")
OUTPUT_FILE_NAME = Path("output_test_file")
KEY_FILE = Path("test_key_file")


class TestCrypting(unittest.TestCase):

    def setUp(self):
        with open(INPUT_FILE_NAME, "wb") as test_file:
            test_file.write(b"Lorem ipsum\r\n")
            test_file.write(b"Lirum larum\r\n")

    def tearDown(self):
        INPUT_FILE_NAME.unlink(missing_ok=True)
        ENCRYPTED_FILE_NAME.unlink(missing_ok=True)
        OUTPUT_FILE_NAME.unlink(missing_ok=True)
        KEY_FILE.unlink(missing_ok=True)

    def test_file_encryption(self):
        """Encrypts and decrypts a file and tests that they are equal
        """
        util.crypting.encrypt_file(INPUT_FILE_NAME, ENCRYPTED_FILE_NAME, KEY_FILE)
        util.crypting.decrypt_file(ENCRYPTED_FILE_NAME, OUTPUT_FILE_NAME, KEY_FILE)
        assert filecmp.cmp(INPUT_FILE_NAME, OUTPUT_FILE_NAME)
```
</details>

Code for my crypting-module is as follows. The place where the exception is raised is marked with comments at the end of this code snippet.

<details>
<summary>Crypting-module</summary>

``` python
import os
import argparse
import logging
from pathlib import Path
from Crypto.Cipher import AES
from Crypto.Random import get_random_bytes
from typing import Union

_logger = logging.getLogger(__name__)


def encrypt_file(input_file: Union[Path, str], output_file: Union[Path, str], key_file: Union[Path, str]):
    """Encrypt file with given AES256 key

    :param input_file: Path-object or string with the path of the raw input file
    :param output_file: Path-object or string with the path of encrypted file
    :param key_file: Path-object with the path of AES256 key.
    If key doesn't exist it will be created with given name
    """
    input_file = Path(input_file)
    output_file = Path(output_file)
    key_file = Path(key_file)

    with open(input_file, "rb") as file_in:
        data = file_in.read()

    if key_file.exists():
        with open(key_file, "rb") as key_file:
            key = key_file.read()

    else:
        key = get_random_bytes(32)
        with open(key_file, "wb") as key_file:
            key_file.write(key)

    cipher = AES.new(key, AES.MODE_EAX)
    ciphertext, tag = cipher.encrypt_and_digest(data)

    with open(output_file, "wb") as file_out:
        [file_out.write(x) for x in (cipher.nonce, tag, ciphertext)]


def decrypt_file(input_file: Union[Path, str], output_file: Union[Path, str], key_file: Union[Path, str]):
    """Decrypt file with given AES256 key

    :param input_file: Path-object or string with the input encrypted file
    :param output_file: Path-object or string with path to the wanted output
    :param key_file: Path-object or string with path to key-file
    """
    _logger.info(f'Decrypting file from path: {input_file}')
    input_file = Path(input_file)
    output_file = Path(output_file)
    key_file = Path(key_file)

    if os.path.isfile(key_file):
        with open(key_file, "rb") as key_file:
            key = key_file.readline()
    else:
        _logger.error('Cryption key missing')
        raise Exception()

    with open(input_file, "rb") as file_in:
        nonce, tag, ciphertext = [file_in.read(x) for x in (16, 16, -1)]

    cipher = AES.new(key, AES.MODE_EAX, nonce)
    try:
        data = cipher.decrypt_and_verify(ciphertext, tag)
    except ValueError:
        msg = 'File decryption failed'
        _logger.exception(msg)
        ##############################
        # Following exception raised #
        ##############################
        raise Exception(msg)

    with open(output_file, "wb") as out_file:
        out_file.write(data)

```
</details>

Following error is noticed in Gitlab CI

<details>
<summary>Error traceback and message</summary>

``` shell
Traceback (most recent call last):
  File "/tmp/builds/7ABqJJkB/0/phoenix/phoenix-app/util/crypting.py", line 75, in decrypt_file
    data = cipher.decrypt_and_verify(ciphertext, tag)
  File "/usr/local/lib/python3.10/site-packages/Crypto/Cipher/_mode_eax.py", line 368, in decrypt_and_verify
    self.verify(received_mac_tag)
  File "/usr/local/lib/python3.10/site-packages/Crypto/Cipher/_mode_eax.py", line 309, in verify
    raise ValueError("MAC check failed")
ValueError: MAC check failed
```
</details>

**Comment by ml-kalju** [comment]
Adding another error that I encounter randomly. I still have no idea what causes these bugs.

```
util/crypting.py:73: in decrypt_file
    cipher = AES.new(key, AES.MODE_EAX, nonce)
/usr/local/lib/python3.10/site-packages/Crypto/Cipher/AES.py:228: in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
/usr/local/lib/python3.10/site-packages/Crypto/Cipher/__init__.py:79: in _create_cipher
    return modes[mode](factory, **kwargs)
/usr/local/lib/python3.10/site-packages/Crypto/Cipher/_mode_eax.py:408: in _create_eax_cipher
    return EaxMode(factory, key, nonce, mac_len, kwargs)
/usr/local/lib/python3.10/site-packages/Crypto/Cipher/_mode_eax.py:107: in __init__
    self._omac = [
/usr/local/lib/python3.10/site-packages/Crypto/Cipher/_mode_eax.py:108: in <listcomp>
    CMAC.new(key,
/usr/local/lib/python3.10/site-packages/Crypto/Hash/CMAC.py:301: in new
    return CMAC(key, msg, ciphermod, cipher_params, mac_len,
/usr/local/lib/python3.10/site-packages/Crypto/Hash/CMAC.py:76: in __init__
    self._ecb = ciphermod.new(key,
/usr/local/lib/python3.10/site-packages/Crypto/Cipher/AES.py:228: in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
/usr/local/lib/python3.10/site-packages/Crypto/Cipher/__init__.py:79: in _create_cipher
    return modes[mode](factory, **kwargs)
/usr/local/lib/python3.10/site-packages/Crypto/Cipher/_mode_ecb.py:216: in _create_ecb_cipher
    cipher_state = factory._create_base_cipher(kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
dict_parameters = {}
    def _create_base_cipher(dict_parameters):
        """This method instantiates and returns a handle to a low-level
        base cipher. It will absorb named parameters in the process."""
    
        use_aesni = dict_parameters.pop("use_aesni", True)
    
        try:
            key = dict_parameters.pop("key")
        except KeyError:
            raise TypeError("Missing 'key' parameter")
    
        if len(key) not in key_size:
>           raise ValueError("Incorrect AES key length (%d bytes)" % len(key))
E           ValueError: Incorrect AES key length (29 bytes)
/usr/local/lib/python3.10/site-packages/Crypto/Cipher/AES.py:90: ValueError
```

**Comment by Varbin** [comment]
```python3
    if os.path.isfile(key_file):
        with open(key_file, "rb") as key_file:
            key = key_file.readline()
    else:
        _logger.error('Cryption key missing')
        raise Exception()

```

This may be the culprit. A randomly generated key can contain line breaks (newline characters). readline() will only read until the line break.

Anyway, here are a few potential improvements for your code:

Additionally the code has a Time-of-check to time-of-use (TOCTOU): `os.path.isfile(keyfile)` may return true, than the file is deleted and after that `open(keyfile)` may be called by your program. Additionally, the `FileNotFoundException` raised by `open(keyfile)` if the file does not exist should already cover missing files.

Further, do not hide error context, if you want to log errors, either reraise the cought exception (`except ValueError as e: ... raise e`) or raise your issue with context (`except ValueError as e: raise Exception('msg') from e`)

**Comment by ml-kalju** [comment]
Thank you @Varbin for your input. That `readline` vs `read` makes sense. I'll also add those other improvements to my code to hopefully get rid of my flaky test problem, or to at least get better logging in case there is some other problem.
