### ISSUE TITLE
Getting NameError ("sys" is not defined), PKCS1_OAEP

### ISSUE THREAD

**Issue by Coal0** [Legrandin/pycryptodome#79]
I'm trying to use RSA for encrypting an AES session key, following [pycryptodome's examples](http://pycryptodome.readthedocs.io/en/latest/src/examples.html). However, when I try to import `PKCS1_OAEP` from `Crypto.Cipher`, I get a `NameError`:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Crypto/Cipher/PKCS1_OAEP.py", line 57, in <module>
    import Crypto.Signature.PKCS1_PSS
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Crypto/Signature/PKCS1_PSS.py", line 70, in <module>
    if sys.version_info[0] == 2 and sys.version_info[1] == 1:
NameError: name 'sys' is not defined`

I am running MacOS El Capitan (10.11.2) with Python 3.6.0.

**Comment by Coal0** [comment]
Unrelated issue. My `pycryptodome` and `pycrypto` installations are mixed.
