### ISSUE TITLE
DSA.py - 'str' object has no attribute 'has_private'

### ISSUE THREAD

**Issue by hoang408** [Legrandin/pycryptodome#98]
I am following the PDF of v.3.4.7, on page 36/82.  The code is encountered right on this line:
f.write(key.publickey().exportKey(key))

I am running on a Windowos 7 machine, so I modify the previous line to:
f = open("public_key.pem", "wb")

This is the error message:
Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\BitBucket\cryptodome\Cryptodome tutorial 3 - Key type, DSA.py", line 8, in <module>
    f.write(key.publickey().exportKey(key))
  File "C:\Program Files\Python36\lib\site-packages\Crypto\PublicKey\DSA.py", line 272, in exportKey
    if format == 'OpenSSH':
  File "C:\Program Files\Python36\lib\site-packages\Crypto\PublicKey\DSA.py", line 163, in __eq__
    if bool(self.has_private()) != bool(other.has_private()):
AttributeError: 'str' object has no attribute 'has_private'

Any help would be appreciated.  Thanks.

**Comment by Varbin** [comment]
If fail with the error
`AttributeError: _DSAobj object has no 'exportKey' attribute`
for the same code. Would you mind sharing your hole code you use?
`

**Comment by Legrandin** [comment]
Closing because of no further activity
